services:

  drupal:
    build: .
    container_name: drupal8
    ports:
      - "8081:80"

    volumes:
      - ./app:/var/www/html

    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: drupal8_mysql

    ports:
      - "3307:3306"

    environment:
      MYSQL_DATABASE: drupal8
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: root

    command: --default-authentication-plugin=mysql_native_password

    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: drupal8_phpmyadmin

    ports:
      - "8082:80"

    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root

    depends_on:
      - mysql

volumes:
  mysql_data: